### ISSUE TITLE
Message: Can’t render a preview. The Content-Type header is missing or unknown.

### ISSUE THREAD

**Issue by fulviocanducci** [benirave/AspNetCore.Scalar#36] opened 2024-05-28 22:50 UTC
A message is appearing: "Unable to render a preview. The Content-Type header is missing or unknown." Why does the result of the GET request not appear?

_Example created in C# MVC API REST_

[
![save1111](https://github.com/benirave/AspNetCore.Scalar/assets/25593291/36dbe942-82e0-4c67-9fc6-16f7dbb63d7d)
](url)

**Comment by benirave** [comment] 2024-06-07 21:50
Hi there,

I just did a quick test and I am having the same issue with the latest version of the package (1.1.1), which uses the scalar version of 1.22.48. As far as I can see other people also experience similar issues and it was already reported on the Scalar repository. ([See here](https://github.com/scalar/scalar/issues/1994)).

For now I would suggest to use 1.1.0 until they fix the problem on their and.

**Comment by rknubreed** [comment] 2024-06-10 15:00
Hi @benirave, looks like this issue is already solved in the latest version of Scalar. Are you able to merge the following PR? https://github.com/benirave/AspNetCore.Scalar/pull/38

**Comment by benirave** [comment] 2024-06-10 22:47
Hi @rknubreed,

Actually, I've already tested the latest scalar version (1.23.5) but I tested it again, and you are right it fixed the issue for me, so I most probably missed something previously. Can you double check just in case that the new version of this package (1.1.2) solves this issue?

**Comment by rknubreed** [comment] 2024-06-11 10:59
Hi @benirave @fulviocanducci ,
I just checked the new package and I can confirm that it works as exepcted - preview is generated.

**Comment by benirave** [comment] 2024-06-11 15:31
Great news, @rknubreed thanks for taking the time!

I am closing the issue.

**Closed by benirave** 2024-06-11 15:31 UTC
Labels: bug, external-issue
